In [1]:
import numpy as np #an arry

x=np.array([2,3,4,5,6])
print(x)
print((type)(x))

[2 3 4 5 6]
<class 'numpy.ndarray'>


In [2]:
y=[2,3,4,5,6] # a  list
print(y)
print(type(y))

[2, 3, 4, 5, 6]
<class 'list'>


In [3]:
%timeit [(j**5) for j in range(1,11)]

2.98 µs ± 215 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
%timeit np.arange(1,11)**4


4.05 µs ± 275 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# ARRAY

In [5]:
x=[1,2,3,4]
y=np.array(x)
print(type(y))
y

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [6]:
l=[]
n=int(input("enter a number:"))
for i in range(1,(n+1)):
    l.append(i)
print(np.array(l))

enter a number:1
[1]


In [7]:
l=[]
n=int(input("enter a number:"))
for i in range(1,(n+1)):
    l.append(i)
print(np.array(l))

enter a number:1
[1]


In [8]:
n = int(input("How many numbers do you want to enter? "))  # Ask the user how many numbers they want to input
l = []  # Initialize an empty list

for i in range(n):  # Loop 'n' times
    number = int(input("Enter a number: "))  # Prompt user to enter a number
    l.append(number)  # Append the number to the list

print(np.array(l))  # Convert the list to a NumPy array and print it


How many numbers do you want to enter? 3
Enter a number: 1
Enter a number: 2
Enter a number: 3
[1 2 3]


### ndim

In [9]:
x=np.array([2,3,4,5,6])
print(x)
print((type)(x))
print(x.ndim)

[2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [10]:
to_d_ary=np.array([[1,2,3,4],[5,6,7,8]])
print(to_d_ary)
print(to_d_ary.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [11]:
thre_d_ary=np.array([[[1,2,3,4],[5,6,7,8],[4,5,6,80]]])
print(thre_d_ary)
print(thre_d_ary.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 4  5  6 80]]]
3


In [12]:
n_d_ary=np.array([1,2,3,4],ndmin=10)
print(n_d_ary)
print(n_d_ary.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Types Of Array

### ZEROS 

In [13]:
ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))

print(ar_zero)
print(" ")
print(ar_zero1)

[0. 0. 0. 0.]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### ONES

In [14]:
ar_zero=np.ones(4)
ar_zero1=np.ones((3,4))

print(ar_zero)
print(" ")
print(ar_zero1)

[1. 1. 1. 1.]
 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### EMPTY

In [15]:
ar_zero=np.empty(4)
ar_zero1=np.empty((3,4))

print(ar_zero)
print(" ")
print(ar_zero1)

[1. 1. 1. 1.]
 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### RANGE

In [16]:
ar_zero=np.arange(4)


print(ar_zero)


[0 1 2 3]


In [17]:
ar_di=np.eye(3)
print(ar_di)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
ar_di=np.eye(6)
print(ar_di)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


## linspace

ar_line=np.linspace(0,10,num=5)
print(ar_line)

# CREATE NUMPAY ARRAY RANDOMLY

## rand() between(0,1)

In [19]:
var=np.random.rand(4)
print(var)

[0.93326045 0.55302046 0.2532249  0.10114078]


In [20]:
var1=np.random.rand(6,4)
print(var1)

[[0.23840946 0.13736441 0.31868137 0.73067912]
 [0.40306448 0.30275361 0.6542972  0.05031557]
 [0.06651392 0.83134776 0.72456119 0.83511895]
 [0.91014178 0.15388027 0.96393163 0.25868309]
 [0.37775523 0.55489854 0.37694533 0.49650264]
 [0.91493698 0.82718383 0.08298447 0.57053728]]


## randn() both +ve and -ve 

In [21]:
var=np.random.randn(5)
print(var)

[-0.78017306 -0.26245693 -0.10182382 -2.09209462 -0.37054583]


## ranf() 1 is not included [0,1)

In [22]:
var=np.random.ranf(6)
print(var)

[0.38718278 0.2210532  0.34626712 0.47258986 0.83511669 0.73516704]


## randint()

In [23]:
var=np.random.randint(4,10,5)
print(var)

[8 9 8 5 7]


In [24]:
var=np.random.randint(4,10)
print(var)

8


In [25]:
from random import randint 
var=np.random.randint(4,10,4)
print(var)

[9 7 4 6]


# DATATYPE

In [26]:
var=np.array([3,5,6,7,8,9,0])
print(f"Data Type:{var.dtype}")

Data Type:int64


In [27]:
var=np.array([3,5,6,7,8,9,0,8.89])
print(f"Data Type:{var.dtype}")

Data Type:float64


In [28]:
var=np.array([3,5,6,7,8,9,0,8.89,"=","h"])
print(f"Data Type:{var.dtype}")

Data Type:<U32


In [29]:
var=np.array(["h",".",">"])
print(f"Data Type:{var.dtype}")

Data Type:<U1


In [30]:
y=np.array([1,2,3,4,5,6])
print(f"Data Type:{y.dtype}")

Data Type:int64


In [31]:
y=np.array([1,2,3,4,5,6],dtype=np.int8)
print(f"Data Type:{y.dtype}")

Data Type:int8


In [32]:
y=np.array([1,2,3,4,5,6],dtype="f")
print(f"Data Type:{y.dtype}")

Data Type:float32


In [33]:
y=np.array([1,2,3,4,5,6],dtype=np.float32)
print(f"Data Type:{y.dtype}")

Data Type:float32


In [34]:
y=np.array([1,2,3,4,5,6])

new=np.float16(y)

print(f"Data Type:{y.dtype}")
print(f"Data Type:{new.dtype}")

print(y)

Data Type:int64
Data Type:float16
[1 2 3 4 5 6]


In [35]:
y=np.array([1,2,3,4,5,6])

new=np.float16(y)
new_one=np.complex128(new)

print(f"Data Type:{y.dtype}")
print(f"Data Type:{new.dtype}")
print(f"Data Type:{new_one.dtype}")

print(y)
print(new)
print(new_one)

Data Type:int64
Data Type:float16
Data Type:complex128
[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


In [36]:
y=np.array([1,2,3,4,5,6])

x=y.astype(float)

print(y)
print(x)

[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]


## SHAPE AND RESHAPE

In [37]:
var=np.array([[1,2,3],[4,5,6]])

print(var)
print("")

print(var.shape)


[[1 2 3]
 [4 5 6]]

(2, 3)


In [38]:
var_1=np.array([1,2,3,4],ndmin=6)

print(var_1,"\n",var_1.ndim)

print(var_1.shape)

[[[[[[1 2 3 4]]]]]] 
 6
(1, 1, 1, 1, 1, 4)


In [39]:
var_2=np.array([1,2,3,4,6,5,7,8])
print(var_2)
print("")
print(var_2.ndim)
print("")

x=var_2.reshape(4,2)

print(x)
print("")
print(x.ndim)

[1 2 3 4 6 5 7 8]

1

[[1 2]
 [3 4]
 [6 5]
 [7 8]]

2


In [40]:
var_2=np.array([1,2,3,4,6,5,7,8,9,10,11,12])
print(var_2)
print("")
print(var_2.ndim)
print("")

x=var_2.reshape(2,2,3) #2 blocks, each containing 2 rows and 3 columns

print(x)
print("")
print(x.ndim)

[ 1  2  3  4  6  5  7  8  9 10 11 12]

1

[[[ 1  2  3]
  [ 4  6  5]]

 [[ 7  8  9]
  [10 11 12]]]

3


In [41]:
var_2=np.array([1,2,3,4,6,5,7,8,9,10,11,12])
print(var_2)
print("")
print(var_2.ndim)
print("")

x=var_2.reshape(2,2,3) #2 blocks, each containing 2 rows and 3 columns

print(x)
print("")
print(x.ndim)

print("")

y=x.reshape(-1)
print(y)
print("")
print(y.ndim)

[ 1  2  3  4  6  5  7  8  9 10 11 12]

1

[[[ 1  2  3]
  [ 4  6  5]]

 [[ 7  8  9]
  [10 11 12]]]

3

[ 1  2  3  4  6  5  7  8  9 10 11 12]

1


# ARITHMATIC OPERATION

### (A+B) , (A-B) , (A*B) , (A/B) , (A**B) ,  (1/A,reciprocal)

In [53]:
var=np.array([1,2,3,4])
var2=np.array([6,5,5,9])

varadd1=var+var2
varadd=var+4

print(varadd1)
print(varadd)

[ 7  7  8 13]
[5 6 7 8]


In [54]:
var=np.array([1,2,3,4])
var2=np.array([6,5,5,9])

varadd1=var-var2
varadd=var-4

print(varadd)
print(varadd1)

[-3 -2 -1  0]
[-5 -3 -2 -5]


In [55]:
var=np.array([1,2,3,4])
var2=np.array([6,5,5,9])

varadd1=var*var2
varadd=var*4

print(varadd1)
print(varadd)

[ 6 10 15 36]
[ 4  8 12 16]


In [56]:
var=np.array([1,2,3,4])
var2=np.array([6,5,5,9])

varadd1=var/var2
varadd=var/4

print(varadd1)
print(varadd)

[0.16666667 0.4        0.6        0.44444444]
[0.25 0.5  0.75 1.  ]


In [59]:
var=np.array([1,2,3,4])
var2=np.array([6,5,5,9])

varadd1=var**var2
varadd=var**2

print(varadd1)
print(varadd)

[     1     32    243 262144]
[ 1  4  9 16]


In [60]:
var=np.array([1,2,3,4])
var2=np.array([6,5,5,9])

varadd1=var%var2
varadd=var%4

print(varadd1)
print(varadd)

[1 2 3 4]
[1 2 3 0]


In [64]:
var2=np.array([1,2,3])
s=var2%4
print(s)

[1 2 3]


## for 2d array

In [65]:
variable_1=np.array([[1,2,3,4],[1,2,3,4]])
variable_2=np.array([[1,2,3,4],[1,2,3,4]])

variable_calculation=variable_1+variable_2

print(variable_calculation)


[[2 4 6 8]
 [2 4 6 8]]


In [66]:
variable_1=np.array([[1,2,3,4],[1,2,3,4]])
variable_2=np.array([[1,2,3,4],[1,2,3,4]])

variable_calculation=variable_1-variable_2

print(variable_calculation)


[[0 0 0 0]
 [0 0 0 0]]


In [67]:
variable_1=np.array([[1,2,3,4],[1,2,3,4]])
variable_2=np.array([[1,2,3,4],[1,2,3,4]])

variable_calculation=variable_1*variable_2

print(variable_calculation)


[[ 1  4  9 16]
 [ 1  4  9 16]]


In [68]:
variable_1=np.array([[1,2,3,4],[1,2,3,4]])
variable_2=np.array([[1,2,3,4],[1,2,3,4]])

variable_calculation=variable_1/variable_2

print(variable_calculation)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [69]:
variable_1=np.array([[1,2,3,4],[1,2,3,4]])
variable_2=np.array([[1,2,3,4],[1,2,3,4]])

variable_calculation=variable_1%variable_2

print(variable_calculation)


[[0 0 0 0]
 [0 0 0 0]]


In [70]:
variable_1=np.array([[1,2,3,4],[1,2,3,4]])
variable_2=np.array([[1,2,3,4],[1,2,3,4]])

variable_calculation=variable_1**variable_2

print(variable_calculation)


[[  1   4  27 256]
 [  1   4  27 256]]


In [75]:
variable_1=np.array([[1,2,3,4],[1,2,3,4]])
variable_2=np.array([[1,2,3,4],[1,2,3,4]])

reciprocal_1 = 1 / variable_1
reciprocal_2 = 1 / variable_2


print("Reciprocal of variable_1:")
print(reciprocal_1)

print("\nReciprocal of variable_2:")
print(reciprocal_2)



Reciprocal of variable_1:
[[1.         0.5        0.33333333 0.25      ]
 [1.         0.5        0.33333333 0.25      ]]

Reciprocal of variable_2:
[[1.         0.5        0.33333333 0.25      ]
 [1.         0.5        0.33333333 0.25      ]]


In [96]:
import numpy as np

# Creating the arrays
variable_1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
variable_2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

# Finding the reciprocal
reciprocal_1 = 1 / variable_1
reciprocal_2 = 1 / variable_2

# Printing the results
print("Reciprocal of variable_1:")
print(reciprocal_1)

print("\nReciprocal of variable_2:")
print(reciprocal_2)

# Combining the results into a single array
combined_reciprocal = np.stack((reciprocal_1, reciprocal_2))
print("\nCombined Reciprocal:")
print(combined_reciprocal)



Reciprocal of variable_1:
[[1.         0.5        0.33333333 0.25      ]
 [1.         0.5        0.33333333 0.25      ]]

Reciprocal of variable_2:
[[1.         0.5        0.33333333 0.25      ]
 [1.         0.5        0.33333333 0.25      ]]

Combined Reciprocal:
[[[1.         0.5        0.33333333 0.25      ]
  [1.         0.5        0.33333333 0.25      ]]

 [[1.         0.5        0.33333333 0.25      ]
  [1.         0.5        0.33333333 0.25      ]]]


In [106]:
import numpy as np

variable_1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
variable_2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

reciprocal_1 = 1 / variable_1
reciprocal_2 = 1 / variable_2

combined_reciprocal = [reciprocal_1, reciprocal_2]

print("Combined Reciprocal:")
for reciprocal in combined_reciprocal:
    print(reciprocal)
    print()  # Prints an empty line for better readability



Combined Reciprocal:
[[1.         0.5        0.33333333 0.25      ]
 [1.         0.5        0.33333333 0.25      ]]

[[1.         0.5        0.33333333 0.25      ]
 [1.         0.5        0.33333333 0.25      ]]



In [107]:
var=np.array([1,2,3,4])

print(f"min:{min(var)},{np.argmax(var)}")
print(f"max:{max(var)},{np.argmin(var)}")


      

min:1,3
max:4,0


In [2]:
import numpy as np
var = np.array([[1, 2, 5, 4], [2, 3, 4, 5]])               #axis"0"=column
print(f"min:{np.min(var,axis=1)},{np.argmin(var,axis=0)}") #axis"1"=row
print(f"max:{np.max(var,axis=1)},{np.argmax(var,axis=0)}")


min:[1 2],[0 0 1 0]
max:[5 5],[1 1 0 1]


In [8]:
var = np.array([[1, 2, 5, 4], [2, 3, 4, 5]]) 
print(f"sqrt:{np.sqrt(var)}\n")
print()
print(f"sin:{np.sin(var)}\n")
print()
print(f"cos:{np.cos(var)}\n")
print()
print(f"cumsum:{np.cumsum(var)}\n")

sqrt:[[1.         1.41421356 2.23606798 2.        ]
 [1.41421356 1.73205081 2.         2.23606798]]


sin:[[ 0.84147098  0.90929743 -0.95892427 -0.7568025 ]
 [ 0.90929743  0.14112001 -0.7568025  -0.95892427]]


cos:[[ 0.54030231 -0.41614684  0.28366219 -0.65364362]
 [-0.41614684 -0.9899925  -0.65364362  0.28366219]]


cumsum:[ 1  3  8 12 14 17 21 26]



# BRODCASTING

In [9]:
import numpy as np
var1=np.array([1,2,3,4])
print(var1.shape,"\n")
  
var2=np.array([[1],[2],[3],[4]])
print(var2.shape,"\n")

print(var1,"\n")
print(var2,"\n")
print(var1+var2)


(4,) 

(4, 1) 

[1 2 3 4] 

[[1]
 [2]
 [3]
 [4]] 

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [2]:
import numpy as np
var3=np.array([[1,2,3]])
print(var3.shape)
print("")
var4=np.array([[[1,2,3],[2,1,3],[3,2,1]]])
print(var4.shape)
print()
print(var3+var4)

(1, 3)

(1, 3, 3)

[[[2 4 6]
  [3 3 6]
  [4 4 4]]]


In [4]:
x=np.array([[1],[2]])
print(x.shape)
print()
y=np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()
print(x+y)

(2, 1)

(2, 3)

[[2 3 4]
 [3 4 5]]


In [8]:
a=np.array([[2],[1]])
print(a.shape)
b=np.array([[1,2,3]])
print(b.shape)
print(a+b)

(2, 1)
(1, 3)
[[3 4 5]
 [2 3 4]]


In [10]:
a=np.array([[2],[1]])
print(a.shape)
b=np.array([[1,2,3],[2,1,3],[3,2,1]])
print(b.shape)
print(a+b)

(2, 1)
(3, 3)


ValueError: operands could not be broadcast together with shapes (2,1) (3,3) 

# INDEXING 

In [23]:
var=np.array([9,8,7,6]) #0,1,2,3
print(var[3])           #-4,-3,-3,-1
print(var[-3])

6
8


In [24]:
var1=np.array([[3,4,5],[6,7,8]])
print(var1.ndim)
print()
print(var1[0,1])

2

4


In [25]:
var2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(var2)
print(var2.ndim)
print(var2[0,1,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
6


# SLICING

In [39]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a[0:9:2])#[start:stop:step]
print(a[3:])
print(a[:5])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[4 5 6 7 8 9]
[1 2 3 4 5]


In [45]:
var2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(var2[0,2,0:2])

[7 8]


In [9]:
k=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(k[1,1:])

[6 7 8]


# NUMPY ARRAY ITERATING

In [18]:
x=np.array([1,2,3,4,5,6,7])
print(x)
print()
for i in x:
    print(i)

[1 2 3 4 5 6 7]

1
2
3
4
5
6
7


In [24]:
var2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(var2)
print()
print(var2.ndim)
print()
for j in var2:
    pass
    
    
for k in var2:
    for l in k:
        for a in l:
            print(a)
        

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

3

1
2
3
4
5
6
7
8
9


In [28]:
var2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(var2):             #function for itretion
    print(i)

1
2
3
4
5
6
7
8
9


In [39]:
var2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(var2,flags=['buffered'],op_dtypes=["S"]): 
    print(i)#used to change the data type
    

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')


In [40]:
var7=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.ndenumerate(var7):             #function to show indxing also
    print(i)

((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 0, 2), np.int64(3))
((0, 1, 0), np.int64(4))
((0, 1, 1), np.int64(5))
((0, 1, 2), np.int64(6))
((0, 2, 0), np.int64(7))
((0, 2, 1), np.int64(8))
((0, 2, 2), np.int64(9))


## COPY AND VIEW 

In [45]:
var=np.array([1,2,3,4])

co=var.copy()

vi=var.view()

print(f"var:{var}\ncopy:{co}\nview:{vi}")


var:[1 2 3 4]
copy:[1 2 3 4]
view:[1 2 3 4]


In [1]:
# Feature	  Copy	                                                                         View
# Definition	Creates a new array and copies the data from the original array.	       |Creates a new array object that looks at the same data as the original array.
# Memory	Allocates new memory for the copied data.	                                   |Does not allocate new memory for the data; it references the same memory as the original array.
# Data Independence	Changes to the data in the copy do not affect the original array.      |Changes to the data in the view affect the original array and vice versa.

## JOIN ARRAY

In [1]:
import numpy as np

var1=np.array([1,2,3,4])
var2=np.array([5,6,7,8])

join=np.concatenate((var1,var2))

print(join)

[1 2 3 4 5 6 7 8]


In [2]:
var3=np.array([[1,2,3],[4,5,6]])
var4=np.array([[5,6,0],[7,8,0]])
join1=np.concatenate((var4,var3),axis=1) #along row
join2=np.concatenate((var4,var3),axis=0) #along column
print(join1,"\n\n",join2)


[[5 6 0 1 2 3]
 [7 8 0 4 5 6]] 

 [[5 6 0]
 [7 8 0]
 [1 2 3]
 [4 5 6]]


In [6]:
# by using"stack"function

vr3=np.array([[1,2,3],[4,5,6]])
vr4=np.array([[5,6,0],[7,8,0]])
joint1=np.stack((vr3,vr4),axis=1) #along row
joint2=np.stack((vr3,vr4),axis=0) #along column
print(joint1,"\n\n",joint2)


[[[1 2 3]
  [5 6 0]]

 [[4 5 6]
  [7 8 0]]] 

 [[[1 2 3]
  [4 5 6]]

 [[5 6 0]
  [7 8 0]]]


In [11]:
var1=np.array([1,2,3,4])
var2=np.array([5,6,7,8])

join1=np.stack((var1,var2),axis=0)
join2=np.stack((var1,var2),axis=1)

print(join1,"\n\n",join2)

[[1 2 3 4]
 [5 6 7 8]] 

 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [15]:
join1=np.hstack((var1,var2)) #h=along row
join2=np.vstack((var1,var2))  #v=along column
join3=np.dstack((var1,var2)) #d=along height
print(join1,"\n\n",join2,"\n\n",join3)

[1 2 3 4 5 6 7 8] 

 [[1 2 3 4]
 [5 6 7 8]] 

 [[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [19]:
join1=np.stack((var1,var2),axis=0) #h=along row
join2=np.stack((var1,var2),axis=1)  #v=along column
join3=np.stack((var1,var2),axis=-1)
print(join1,"\n\n",join2,"\n\n",join3)

[[1 2 3 4]
 [5 6 7 8]] 

 [[1 5]
 [2 6]
 [3 7]
 [4 8]] 

 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


## SPLIT ARRAY

In [39]:
# when NOT equaly divide
vr1=np.array([1,2,3,4])

print(vr1)
print()
ar=np.array_split(vr1,[1,3])
print()
print(ar)
print(ar[1])

[1 2 3 4]


[array([1]), array([2, 3]), array([4])]
[2 3]


In [36]:
# use of AXIS
import numpy as np

# Create a 2D array
arr = np.arange(16).reshape(4, 4)
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11],
#        [12, 13, 14, 15]])

# Split the array into 2 equal parts along the columns (axis=1)
split_arr = np.split(arr, 2, axis=0)

print(split_arr)
# Output: [array([[ 0,  1],
#                 [ 4,  5],
#                 [ 8,  9],
#                 [12, 13]]), 
#          array([[ 2,  3],
#                 [ 6,  7],
#                 [10, 11],
#                 [14, 15]])]


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [32]:
# SPLITTING IN EQUAL PARTS

# Create an array
arr = np.arange(9)  # array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Split the array into 3 equal parts
split_arr = np.split(arr, 3)

print(split_arr)
# Output: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [42]:
#SPLITING IN SPECIFIC INDICES

# Create an array
arr = np.arange(9)  # array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Split the array at indices 3 and 6
split_arr = np.split(arr, [3, 4])

print(split_arr)
# Output: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
print()
print(split_arr[0])

[array([0, 1, 2]), array([3]), array([4, 5, 6, 7, 8])]

[0 1 2]


In [45]:
arr = np.arange(16).reshape(2, 8)
print(arr)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


## search

In [47]:
arr = np.arange(16).reshape(4, 4)
x=np.where(arr==14)
print(x,"\n\n")
print(arr)

(array([3]), array([2])) 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [3]:
import numpy as np
array = np.array([16,12,14,15,5,6,7,14,7,8,9,0])
y=np.where((array%2)==0)
print(y,"\n\n")
print(array)

(array([ 0,  1,  2,  5,  7,  9, 11]),) 


[16 12 14 15  5  6  7 14  7  8  9  0]


In [11]:
array = np.array([16,12,14,15,5,6,7,14,7,8,9,0])
a=np.sort(array)
print(a)

a1=np.searchsorted(a,10)
print(a1)

[ 0  5  6  7  7  8  9 12 14 14 15 16]
7


In [20]:
array = np.array([16,12,14,15,5,6,7,14,7,8,9,0,10,23,45,67])
a=np.sort(array)
print(a)

a1=np.searchsorted(a,[10,1,4,6,55],side="left")
print(a1)
print()


[ 0  5  6  7  7  8  9 10 12 14 14 15 16 23 45 67]
[ 7  1  1  2 15]



In [21]:
array = np.array(["a","n","h","g","d","b","y","z"])
a=np.sort(array)
print(a)

['a' 'b' 'd' 'g' 'h' 'n' 'y' 'z']


In [25]:
arr1=np.arange(16).reshape(4,4)
a=np.sort(arr1)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
array = np.array(["a","n","h","g","d","b"])
f=[True,False,False,False,True,True]
new_arr=array[f]
print(new_arr)

['a' 'd' 'b']


## NUMPY FUNCTIONS

In [29]:
#random
var=np.array([1,2,3,4,5,6,7,8,9])
x=np.random.shuffle(var)
print(var)

[2 7 1 4 6 5 8 9 3]


In [37]:
#unique
var1=np.array([1,1,1,2,3,3,4,5,6,7,8,8,9,5,6,7,7,5,5,6,7])
a=np.unique(var1,return_index=True,return_counts=True)
print(a)
s=np.sort(var1)
print("")
print(s)



(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  3,  4,  6,  7,  8,  9, 10, 12]), array([3, 1, 2, 1, 4, 3, 4, 2, 1]))

[1 1 1 2 3 3 4 5 5 5 5 6 6 6 7 7 7 7 8 8 9]


In [40]:
#resize
var1=np.array([1,1,1,2,3,3,4,5,6,7,8,8,9,5,6,7,7,5,5,6,7])

r=np.resize(var1,(4,4))

print(r)

[[1 1 1 2]
 [3 3 4 5]
 [6 7 8 8]
 [9 5 6 7]]


In [45]:
#flatten-->convert 2d arry to 1d array
var1=np.array([1,1,1,2,3,3,4,5,6,7,8,8,9,5,6,7,7,5,5,6,7])

r=np.resize(var1,(4,4))
print(r)
print("")
print(r.flatten(order="c"))


[[1 1 1 2]
 [3 3 4 5]
 [6 7 8 8]
 [9 5 6 7]]

[1 1 1 2 3 3 4 5 6 7 8 8 9 5 6 7]


In [59]:
#ravel
var1=np.array([1,1,1,2,3,3,4,5,6,7,8,8,9,5,6,7,7,5,5,6,7])

r=np.resize(var1,(4,4))
print(r)
print("")
print(np.ravel(r,order="K"))
# print(r.flatten(order="F"))

[[1 1 1 2]
 [3 3 4 5]
 [6 7 8 8]
 [9 5 6 7]]

[1 1 1 2 3 3 4 5 6 7 8 8 9 5 6 7]


# INSERT

In [65]:
g=np.array([1,2,3,4.5,5,6.8,7])

print(g)

print(type(g))

h=np.insert(g,4,[5,6,7,8])
print(h)

[1.  2.  3.  4.5 5.  6.8 7. ]
<class 'numpy.ndarray'>
[1.  2.  3.  4.5 5.  6.  7.  8.  5.  6.8 7. ]


In [68]:
h=np.arange(6).reshape(2,3)
print(h)
print("")

j=np.insert(h,(1,3),6 )
print(j)

[[0 1 2]
 [3 4 5]]

[0 6 1 2 6 3 4 5]


In [74]:
h=np.arange(6).reshape(2,3)
print(h)
print("")

j=np.insert(h,(3),6,axis=1 )
print(j)

[[0 1 2]
 [3 4 5]]

[[0 1 2 6]
 [3 4 5 6]]


In [76]:
# append function
h=np.arange(6).reshape(2,3)
print(h)
print("")

j=np.append(h,(3.7) )
print(j)

[[0 1 2]
 [3 4 5]]

[0.  1.  2.  3.  4.  5.  3.7]


In [83]:
h=np.arange(16).reshape(4,4)
print(h)
print("")

j=np.append(h,[[1,2,3,4]],axis=0 )
print(j)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 1  2  3  4]]


## DELETE

In [93]:
h=np.arange(16).reshape(4,4)
print(h)
print("")
k=np.delete(h,(1,2),axis=1)
print(k)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]]


In [2]:
import numpy as np
h=np.arange(16)
print(h)
print("")
k=np.delete(h,(1,2))
print(k)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[ 0  3  4  5  6  7  8  9 10 11 12 13 14 15]


# MATRIX

In [19]:
var=np.matrix([[1,2,3],[1,2,3],[1,2,3]])
var2=np.matrix([[1,2,3],[1,2,3],[1,2,3]])

print(var)
print()
print(var.ndim)
print(var.shape)
print(type(var))

print(var.dot(var2))

[[1 2 3]
 [1 2 3]
 [1 2 3]]

2
(3, 3)
<class 'numpy.matrix'>
[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


In [20]:
var=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
var1=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(var)
print()
print(var.ndim)
print(var.shape)
print(type(var))

print(var.dot(var2))

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]

3
(1, 3, 3)
<class 'numpy.ndarray'>
[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


 ## MATRIX FUNCTION

In [23]:
#TRANSPOSE

var=np.matrix([[5,2,3],[6,2,3],[8,2,7]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)

[[5 2 3]
 [6 2 3]
 [8 2 7]]

[[5 6 8]
 [2 2 2]
 [3 3 7]]

[[5 6 8]
 [2 2 2]
 [3 3 7]]


In [26]:
#SWAPAAXES
var=np.matrix([[5,2,3],[6,2,3],[8,2,7]])
print(var)
print()


print(np.swapaxes(var,0,1))

[[5 2 3]
 [6 2 3]
 [8 2 7]]

[[5 6 8]
 [2 2 2]
 [3 3 7]]


In [30]:
var2=np.arange(16).reshape(4,4)
print(type(var2))

<class 'numpy.ndarray'>


In [35]:
a=matrix=np.matrix(var2)
print(var2)
print(type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
<class 'numpy.matrix'>


In [33]:
# Create a 3-dimensional array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:")
print(array_3d)

# Reshape the 3D array into a 2D array
array_2d_from_3d = array_3d.reshape(-1, array_3d.shape[-1])
print("\nReshaped to 2D Array:")
print(array_2d_from_3d)

# Convert the reshaped 2D array to a matrix
matrix_from_3d = np.matrix(array_2d_from_3d)
print("\nConverted Matrix from 3D Array:")
print(matrix_from_3d)
print(type(matrix_from_3d))


3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Reshaped to 2D Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Converted Matrix from 3D Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.matrix'>


In [43]:
#INVERSE
var_3=np.matrix([[1,2,3],[3,4,5],[7,9,9]])
print(var_3)
print()
print(np.linalg.inv(var_3))

[[1 2 3]
 [3 4 5]
 [7 9 9]]

[[-2.25  2.25 -0.5 ]
 [ 2.   -3.    1.  ]
 [-0.25  1.25 -0.5 ]]


In [46]:
#POWER
var_4=np.matrix([[1,2,3],[1,4,3],[5,6,7]])

print(var_4)

# p=np.linalg.matrix_power(var,n) #n=0(identity matrix)| n>0(power multiply)|n<0(invers X power)
p=np.linalg.matrix_power(var_4,2)
print()
print(p)


[[1 2 3]
 [1 4 3]
 [5 6 7]]

[[18 28 30]
 [20 36 36]
 [46 76 82]]


In [47]:
#POWER
var_4=np.matrix([[1,2,3],[1,4,3],[5,6,7]])

print(var_4)

# p=np.linalg.matrix_power(var,n) #n=0(identity matrix)| n>0(power multiply)|n<0(invers X power)
p=np.linalg.matrix_power(var_4,0)
print()
print(p)


[[1 2 3]
 [1 4 3]
 [5 6 7]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [48]:
#POWER
var_4=np.matrix([[1,2,3],[1,4,3],[5,6,7]])

print(var_4)

# p=np.linalg.matrix_power(var,n) #n=0(identity matrix)| n>0(power multiply)|n<0(invers X power)
p=np.linalg.matrix_power(var_4,-2)
print()
print(p)


[[1 2 3]
 [1 4 3]
 [5 6 7]]

[[ 0.84375 -0.0625  -0.28125]
 [ 0.0625   0.375   -0.1875 ]
 [-0.53125 -0.3125   0.34375]]


In [57]:
#DETERMINANT 
n=np.arange(9).reshape(3,3)
print(n)

#to find determinant
np.linalg.det(n)

var_4=np.matrix([[1,2,3],[1,4,3],[5,6,7]])
print()
print(np.linalg.det(var_4))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

-15.999999999999998
